spring:
  application:
    name: DigitalPlatform
  datasource:
    url: jdbc:h2:file:/data/demo
    #url: jdbc:h2:mem:testdb
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    generate-ddl: false
    #generate-ddl: true
    hibernate:
      ddl-auto: none
      #ddl-auto: create
      show-sql: true
      format_sql: true
    show-sql: true
  sql:
    init:
      mode: always

generators:
  type: BACKPACK_BELLMAN
logging:
  level:
    com:
      example:
        digitalplatform: DEBUG




